namespace SmartiePaws.Inventory.Core.Entities.Catalog;

/// <summary>
/// The "parent" record for a sellable item -- information shared across all of its variants
/// (name, description, brand). Actual stock levels and pricing live on
/// <see cref="ProductVariant"/>, not here, so one Product can represent something sold in
/// multiple variations without repeating this shared information for each one.
/// </summary>
public class Product
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// The product's display name, e.g. "Dog Treats -- Chicken Jerky."
  /// </summary>
  public string Name { get; set; } = string.Empty;

  /// <summary>
  /// A longer free-text description, for anything that doesn't fit in the name.
  /// </summary>
  public string? Description { get; set; }

  /// <summary>
  /// The manufacturer or brand name, if relevant to how the catalog is organized.
  /// </summary>
  public string? Brand { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while the product is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
