namespace SmartiePaws.Inventory.Core.Entities.Catalog;

/// <summary>
/// One specific, actually-sellable version of a <see cref="Product"/> -- this is the row that
/// carries a SKU, a price, and a stock count. For a product that doesn't vary, there's simply one
/// ProductVariant per Product; this split only pays for itself once a Product genuinely has more
/// than one purchasable option.
/// </summary>
public class ProductVariant
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// Foreign key to the parent product this variant belongs to.
  /// </summary>
  public Guid ProductId { get; set; }

  /// <summary>
  /// Navigation to the parent product. Only populated when explicitly requested.
  /// </summary>
  public Product Product { get; set; } = null!;

  /// <summary>
  /// The variant's unique stock-keeping unit code -- what you'd print on a label or look up by.
  /// Unique across the catalog.
  /// </summary>
  public string Sku { get; set; } = string.Empty;

  /// <summary>
  /// The current price charged for this variant. Used as the default when ringing up a sale; a
  /// SaleLineItem can still charge a different price if discounted.
  /// </summary>
  public decimal Price { get; set; }

  /// <summary>
  /// A cached running total of how many units are currently in stock. The real source of truth
  /// is the sum of <c>QuantityRemaining</c> across this variant's PurchaseOrderLineItem rows --
  /// this column exists purely so the current stock level doesn't have to be re-summed every
  /// time it's displayed.
  /// </summary>
  public int QuantityOnHand { get; set; }

  /// <summary>
  /// An optional threshold. Once QuantityOnHand drops to or below this number, a dashboard can
  /// flag it as running low.
  /// </summary>
  public int? ReorderPoint { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while the variant is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
