namespace SmartiePaws.Inventory.Core.Entities.Catalog;

/// <summary>
/// One image belonging to a <see cref="ProductVariant"/>. A variant can have multiple images, so
/// this is a normal one-to-many table rather than part of <see cref="ProductVariantDetails"/>'s
/// jsonb bag -- every image has the same fixed shape (a reference plus a sort order), which is
/// exactly what a relational table is for. Only ever stores a reference to the image, never the
/// image bytes themselves -- those live in S3 (or a self-hosted S3-compatible store). Not part of
/// the MVP yet -- planned ahead so <see cref="ProductVariant"/> doesn't need a disruptive schema
/// change later.
/// </summary>
public class ProductImage
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// Foreign key to the variant this image belongs to.
  /// </summary>
  public Guid ProductVariantId { get; set; }

  /// <summary>
  /// Navigation to the variant. Only populated when explicitly requested.
  /// </summary>
  public ProductVariant ProductVariant { get; set; } = null!;

  /// <summary>
  /// The image's path/key within the S3 bucket (e.g. "products/abc123/front.jpg"), not a full
  /// URL. The bucket domain/CDN is an infrastructure detail that can change later (move from
  /// local MinIO to real AWS S3, add a CDN in front, etc.); storing just the key means only the
  /// app's base-URL config changes when that happens, not every row in this table.
  /// </summary>
  public string ObjectKey { get; set; } = string.Empty;

  /// <summary>
  /// Controls display order. The image with the lowest SortOrder is treated as the
  /// primary/thumbnail image, rather than using a separate IsPrimary boolean that could end up
  /// marking more than one image primary by mistake.
  /// </summary>
  public int SortOrder { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while the image is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
