namespace SmartiePaws.Inventory.Core.Entities.Purchasing;

/// <summary>
/// One product within a <see cref="PurchaseOrder"/> -- the line, mirroring
/// <see cref="Entities.Sales.SaleLineItem"/>. This table doubles as the FIFO "lot" for that batch
/// of stock: <see cref="QuantityRemaining"/> starts equal to <see cref="QuantityPurchased"/> and
/// counts down as that specific batch gets sold, so profit/cost-of-goods numbers reflect what was
/// actually paid for the units sold, not just today's price.
/// </summary>
public class PurchaseOrderLineItem
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// Foreign key to the order this line belongs to. Required -- every line item belongs to
  /// exactly one order.
  /// </summary>
  public Guid PurchaseOrderId { get; set; }

  /// <summary>
  /// Navigation to the order. Only populated when explicitly requested.
  /// </summary>
  public PurchaseOrder PurchaseOrder { get; set; } = null!;

  /// <summary>
  /// Foreign key to the variant this line restocked.
  /// </summary>
  public Guid ProductVariantId { get; set; }

  /// <summary>
  /// How many units of this line were bought. Never changes after the row is created -- it's the
  /// permanent historical record of what was ordered.
  /// </summary>
  public int QuantityPurchased { get; set; }

  /// <summary>
  /// How many units from this specific batch are still unsold. Starts equal to
  /// <see cref="QuantityPurchased"/> and decreases as sales (or future adjustments) consume from
  /// it, oldest order first -- FIFO.
  /// </summary>
  public int QuantityRemaining { get; set; }

  /// <summary>
  /// The landed cost per unit: this line's item cost plus its pro-rated share of the order's
  /// <see cref="PurchaseOrder.ShippingCost"/>, divided by quantity. This is what cost-of-goods-sold
  /// is based on for any sale that draws from this batch.
  /// </summary>
  public decimal UnitCost { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while this line is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
