namespace SmartiePaws.Inventory.Core.Entities.Purchasing;

/// <summary>
/// A single restock order placed with a <see cref="Vendor"/> -- the header, mirroring
/// <see cref="Entities.Sales.Sale"/>. One order commonly covers multiple different products at
/// once with one shared shipping charge, which is why <see cref="VendorId"/> and
/// <see cref="ShippingCost"/> live here, once per order, rather than being duplicated on every
/// <see cref="PurchaseOrderLineItem"/>.
/// </summary>
public class PurchaseOrder
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// Foreign key to who the whole order was placed with.
  /// </summary>
  public Guid VendorId { get; set; }

  /// <summary>
  /// Navigation to the vendor. Only populated when explicitly requested.
  /// </summary>
  public Vendor Vendor { get; set; } = null!;

  /// <summary>
  /// When the order was placed/received. Lives here rather than on each line item since every
  /// line in one order shares the same date -- FIFO consumption sorts by this via a join to the
  /// order, rather than duplicating a date on every line.
  /// </summary>
  public DateTimeOffset OrderedAt { get; set; }

  /// <summary>
  /// The total shipping charge for the entire order, if any. Gets divided pro-rata across the
  /// order's line items (by their value) when computing each line's landed
  /// <see cref="PurchaseOrderLineItem.UnitCost"/>.
  /// </summary>
  public decimal? ShippingCost { get; set; }

  /// <summary>
  /// Free-form notes about the order as a whole (e.g. an invoice/reference number).
  /// </summary>
  public string? Notes { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while the order is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
