namespace SmartiePaws.Inventory.Core.Entities.Purchasing;

/// <summary>
/// A supplier inventory is bought from. Every <see cref="PurchaseOrder"/> references a Vendor to
/// record who an order was placed with. Vendors are global in this MVP -- there's no per-tenant
/// scoping.
/// </summary>
public class Vendor
{
  /// <summary>
  /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
  /// </summary>
  public Guid Id { get; set; }

  /// <summary>
  /// The vendor's business name. Required -- a vendor record with no name isn't identifiable.
  /// </summary>
  public string Name { get; set; } = string.Empty;

  /// <summary>
  /// A specific person to contact at the vendor, if known.
  /// </summary>
  public string? ContactName { get; set; }

  /// <summary>
  /// Contact email, if known.
  /// </summary>
  public string? Email { get; set; }

  /// <summary>
  /// Contact phone number, if known.
  /// </summary>
  public string? Phone { get; set; }

  /// <summary>
  /// Mailing or physical address, if known.
  /// </summary>
  public string? Address { get; set; }

  /// <summary>
  /// Free-form notes -- account numbers, special terms, anything else worth remembering.
  /// </summary>
  public string? Notes { get; set; }

  /// <summary>
  /// UTC timestamp set by the database when this row was first inserted.
  /// </summary>
  public DateTimeOffset CreatedAt { get; set; }

  /// <summary>
  /// UTC timestamp set by the database on insert and advanced on every subsequent update.
  /// </summary>
  public DateTimeOffset UpdatedAt { get; set; }

  /// <summary>
  /// UTC timestamp of a soft delete. Null while the vendor is active.
  /// </summary>
  public DateTimeOffset? DeletedAt { get; set; }
}
