namespace SmartiePaws.Inventory.Core.Entities;

/// <summary>
/// The top-level tenant. Owns one or more <see cref="Space"/>s and has members via
/// <see cref="OrganizationMembership"/>. Vendors (not yet implemented) are also organization-wide.
/// </summary>
public class Organization
{
    /// <summary>
    /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Display name of the organization.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp set by the database when this row was first inserted.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp set by the database on insert and advanced on every subsequent update.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of a soft delete. Null while the organization is active.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; set; }
}
