namespace SmartiePaws.Inventory.Core.Entities;

/// <summary>
/// A team/workspace scope within an <see cref="Organization"/>. Product catalog, sales, and
/// purchasing all live within a Space, so different teams in the same organization can keep
/// separate data while sharing the same organization and user pool.
/// </summary>
public class Space
{
    /// <summary>
    /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key to the owning organization. Set/queried directly without loading
    /// <see cref="Organization"/>.
    /// </summary>
    public Guid OrganizationId { get; set; }

    /// <summary>
    /// Navigation to the owning organization. Only populated when explicitly requested
    /// (e.g. via <c>.Include(s => s.Organization)</c>); otherwise null.
    /// </summary>
    public Organization Organization { get; set; } = null!;

    /// <summary>
    /// Display name of the Space, e.g. "Retail Team" or "Online Store".
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Optional longer description of what this Space is for.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// UTC timestamp set by the database when this row was first inserted.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp set by the database on insert and advanced on every subsequent update.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of a soft delete. Null while the Space is active.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; set; }
}
