using SmartiePaws.Inventory.Core.Enums;

namespace SmartiePaws.Inventory.Core.Entities.Identity;

/// <summary>
/// Grants a <see cref="User"/> a role within an <see cref="Organization"/>. See
/// <see cref="OrganizationRole"/> for what each role can do.
/// </summary>
public class OrganizationMembership
{
    /// <summary>
    /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key to the organization this membership grants access to.
    /// </summary>
    public Guid OrganizationId { get; set; }

    /// <summary>
    /// Navigation to the organization. Only populated when explicitly requested.
    /// </summary>
    public Organization Organization { get; set; } = null!;

    /// <summary>
    /// Foreign key to the user this membership belongs to.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation to the user. Only populated when explicitly requested.
    /// </summary>
    public User User { get; set; } = null!;

    /// <summary>
    /// The user's role within this organization.
    /// </summary>
    public OrganizationRole Role { get; set; }

    /// <summary>
    /// UTC timestamp set by the database when this row was first inserted.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp set by the database on insert and advanced on every subsequent update.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of a soft delete (i.e. removal from the organization). Null while active.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; set; }
}
