using SmartiePaws.Inventory.Core.Enums;

namespace SmartiePaws.Inventory.Core.Entities.Identity;

/// <summary>
/// Grants a <see cref="User"/> a role within a single <see cref="Space"/>. Only meaningful for a
/// user whose <see cref="OrganizationRole"/> is <see cref="OrganizationRole.Member"/> — an
/// organization Admin or Owner already has full access to every Space without one of these.
/// See <see cref="SpaceRole"/> for what each role can do.
/// </summary>
public class SpaceMembership
{
    /// <summary>
    /// Primary key. Generated by Postgres (<c>gen_random_uuid()</c>) on insert.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Foreign key to the Space this membership grants access to.
    /// </summary>
    public Guid SpaceId { get; set; }

    /// <summary>
    /// Navigation to the Space. Only populated when explicitly requested.
    /// </summary>
    public Space Space { get; set; } = null!;

    /// <summary>
    /// Foreign key to the user this membership belongs to.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation to the user. Only populated when explicitly requested.
    /// </summary>
    public User User { get; set; } = null!;

    /// <summary>
    /// The user's role within this Space.
    /// </summary>
    public SpaceRole Role { get; set; }

    /// <summary>
    /// UTC timestamp set by the database when this row was first inserted.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp set by the database on insert and advanced on every subsequent update.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of a soft delete (i.e. removal from the Space). Null while active.
    /// </summary>
    public DateTimeOffset? DeletedAt { get; set; }
}
