<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartiePaws.Inventory.Data\SmartiePaws.Inventory.Data.csproj" />
    <ProjectReference Include="..\SmartiePaws.Inventory.Core\SmartiePaws.Inventory.Core.csproj" />
  </ItemGroup>

</Project>
